### ISSUE TITLE
Reference callout

### ISSUE THREAD

**Issue by lfoppiano** [SoFairOA/Dataset#12]
@kermitt2, the reference callout (optional) should be annotated with the [grobid style](https://grobid.readthedocs.io/en/latest/training/fulltext/#bibliographical-reference-markers-callouts)? 

Meaning, this: 

```The atomics coordinates of the CDK6 structure were downloaded from the Protein Data Bank (PDB ID -3NUP) and subsequently optimized for modeling the gap in the structures using the "<rs xml:id="12893292" type="software">PRIME</rs>" module of <rs xml:id="12893293" type="publisher" corresp="12893292">Schrödinger</rs> <rs xml:id="12953642" type="bibr">[47,48]</rs>.```

over: 
```The atomics coordinates of the CDK6 structure were downloaded from the Protein Data Bank (PDB ID -3NUP) and subsequently optimized for modeling the gap in the structures using the "<rs xml:id="12893292" type="software">PRIME</rs>" module of <rs xml:id="12893293" type="publisher" corresp="12893292">Schrödinger</rs> [<rs xml:id="12953642" type="bibr">47</rs>,<rs xml:id="12893295" type="bibr">48</rs>].```

or it does not matter? 

I will add the specific way with an example in the guidelines

**Comment by kermitt2** [comment]
It does currently not matter.

**Comment by lfoppiano** [comment]
Thanks!
