### ISSUE TITLE
Algorithm vs software

### ISSUE THREAD

**Issue by lfoppiano** [SoFairOA/Dataset#13]
Some additional clarification on algorithm vs software.

Here, data annotated by 3rd party, one functionality (`steepest descent algorithm`) has been marked as software: 
```
Furthermore, the <rs xml:id="12893315" type="software" subtype="implicit" corresp="12893316">steepest descent algorithm</rs> present in the <rs xml:id="12893316" type="software" subtype="environment">GROMACS</rs> was used for minimizing the neutralized solvated system with a convergence criterion of 0.005 kcal/mol. To keep the ligand molecules in the solvated box, the position restraints were applied.
</p>
```

And here it was not: 

```
<rs xml:id="12893303" type="software">AutoGrid</rs> with a spacing of 0.375 Å. The maximum efficiency values were set for the Lamarckian genetic algorithm, with the population control was set to 250 as well as the "longer" intervals, which were used for the energy evaluations.
```

Following the guidelines, in general, if there is no overlapping between the implementing software and the algorithm, then we should not annotate. This seems the situation for both these cases, or I'm misunderstanding something? 

cc @kermitt2

**Comment by kermitt2** [comment]
I suppose in the first case there is an explicit reference of the implementation framework on which the algorithm is implemented (GROMACS). So the "algorithm" mention is referencing a particular implementation of this algorithm ("present in"). This might put some weight toward annotating it as a software. However, I agree that it's more a functionality of GROMACS that is discussed here and it might be better not to annotate it.

**Comment by lfoppiano** [comment]
Thanks! :-)
